### ISSUE TITLE
[256]android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

### ISSUE THREAD

**Issue by marvel00000** [hyb1996-guest/auto.js3-issues#26691]
Description:
---

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:922)
	at android.app.ContextImpl.startActivity(ContextImpl.java:898)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:389)
	at com.stardust.scriptdroid.ui.common.ScriptOperations.createShortcut(ScriptOperations.java:222)
	at com.stardust.scriptdroid.ui.main.scripts.ScriptListView.onMenuItemClick(ScriptListView.java:236)
	at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:105)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:776)
	at com.android.internal.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:82)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1192)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3184)
	at android.widget.AbsListView$3.run(AbsListView.java:4166)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6809)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

Device info:
---
<table>
<tr><td>App version</td><td>3.1.0 Beta</td></tr>
<tr><td>App version code</td><td>256</td></tr>
<tr><td>Android build version</td><td>9.5.9</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180729.001</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>dipper</td></tr>
<tr><td>Device model</td><td>MI 8</td></tr>
<tr><td>Device product name</td><td>dipper</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by marvel00000** [comment]
版本问题，换了新的release版本，问题解决了。抱歉
