### ISSUE TITLE
[238]java.lang.RuntimeException: Unable to start activity ComponentInfo{com.stardust.scriptdroid/com.stardust.autojs.execution.ScriptExecuteActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by hyb1996-guest** [hyb1996-guest/auto.js3-issues#3]
Description:
---

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.stardust.scriptdroid/com.stardust.autojs.execution.ScriptExecuteActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3184)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3279)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1881)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7406)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
	at com.stardust.util.IntentExtras.get(IntentExtras.java:53)
	at com.stardust.autojs.execution.ScriptExecuteActivity.onCreate(ScriptExecuteActivity.java:44)
	at android.app.Activity.performCreate(Activity.java:7365)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3137)
	... 9 more

Device info:
---
<table>
<tr><td>App version</td><td>3.0.0 Alpha38</td></tr>
<tr><td>App version code</td><td>238</td></tr>
<tr><td>Android build version</td><td>122(C00)</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>BKL-AL20 8.0.0.122(C00)</td></tr>
<tr><td>Device brand</td><td>HONOR</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWBKL</td></tr>
<tr><td>Device model</td><td>BKL-AL20</td></tr>
<tr><td>Device product name</td><td>BKL-AL20</td></tr>
<tr><td>Device hardware name</td><td>kirin970</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by clearw5** [comment]
duplicated with #5
